# Generated by Django 6.0 on 2026-01-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_myuser_adresse_mail_permanente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Photo_portrait',
            field=models.ImageField(upload_to='djangotutorial/media/images'),
        ),
    ]
