# Generated by Django 6.0 on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_photo_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='form_complete',
            field=models.BooleanField(default=False),
        ),
    ]
