# Generated by Django 6.0 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_form_complete_to_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Photo_portrait',
            field=models.ImageField(upload_to='images'),
        ),
    ]
