# Generated by Django 6.0 on 2026-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_myuser_photo_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Photo_portrait',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Statut_etudiant_entrepreneur',
            field=models.BooleanField(default=False),
        ),
    ]
