# Generated by Django 6.0 on 2026-02-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_photo_portrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Adresse_mail_permanente',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Bibliographie1',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Bibliographie2',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Bibliographie3',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Double_diplome',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Duree_de_confidentialite',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Etablissement_formation_3A',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Fonction_tuteur_academique',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Fonction_tuteur_professionnel',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Langue_de_redaction',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Legende',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Mots_cles_EN',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Mots_cles_FR',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Nom_Du_Photographe',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Nom_Image_associee',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Organisme_du_PFE',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Organisme_rattachement_tuteur_academique',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Photo_portrait',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Prenom_NOM',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Presentation_contexte_EN',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Presentation_contexte_FR',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Presentation_missions_EN',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Presentation_missions_FR',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Profil',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Promotion',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Resume_EN',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Resume_FR',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Thematique_principale',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Titre_PFE_EN',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Titre_PFE_FR',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Titre_parcours_3A',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Tuteur_academique',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Tuteur_professionnel',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Type_de_PFE',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Type_organisme_accueil',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
