# Generated by Django 6.0 on 2026-01-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPFE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
