# Generated by Django 6.0 on 2026-01-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('departement_enseignement', models.CharField(blank=True, help_text='z.B. GCC, IMI, SEGF, GI', max_length=50)),
                ('prenom_nom', models.CharField(blank=True, max_length=200)),
                ('adresse_mail_permanente', models.EmailField(blank=True, max_length=254)),
                ('statut_etudiant_entrepreneur', models.CharField(blank=True, max_length=100)),
                ('profil', models.CharField(blank=True, max_length=100)),
                ('double_diplome', models.CharField(blank=True, max_length=200)),
                ('titre_parcours_3a', models.CharField(blank=True, max_length=200)),
                ('etablissement_formation_3a', models.CharField(blank=True, max_length=200)),
                ('promotion', models.CharField(blank=True, max_length=50)),
                ('photo_portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Student User',
                'verbose_name_plural': 'Student Users',
                'db_table': 'users',
            },
        ),
    ]
