# Generated by Django 6.0 on 2026-01-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='adresse_mail_permanente',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='departement_enseignement',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='double_diplome',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='etablissement_formation_3a',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='photo_portrait',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='prenom_nom',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profil',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='statut_etudiant_entrepreneur',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='titre_parcours_3a',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Bibliographie1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Bibliographie2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Bibliographie3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='CHECK_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='CHECK_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='CHECK_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Duree_de_confidentialite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Fonction_tuteur_academique',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Fonction_tuteur_professionnel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Langue_de_redaction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Legende',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Mots_cles_EN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Mots_cles_FR',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Nom_Du_Photographe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Nom_Image_associee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Organisme_du_PFE',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Organisme_rattachement_tuteur_academique',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Presentation_contexte_EN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Presentation_contexte_FR',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Presentation_missions_EN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Presentation_missions_FR',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Resume_EN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Resume_FR',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Si_PFE_Confidentiel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Si_PFE_Non_confidentiel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Thematique_principale',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Titre_PFE_EN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Titre_PFE_FR',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Tuteur_academique',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Tuteur_professionnel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Type_de_PFE',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Type_organisme_accueil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Adresse_mail_permanente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Departement_Enseignement',
            field=models.CharField(default='not_chosen', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Double_diplome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Etablissement_formation_3A',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Photo_portrait',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Prenom_NOM',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Profil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Promotion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Statut_etudiant_entrepreneur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Titre_parcours_3A',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
